server:
  port: 8080

auth:
  jwt:
    accessTokenExpirationTime: 3000
    refreshTokenExpirationTime: 604800

spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: blog